# Copyright 2020 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: check whether cert-manager applied or not
  shell:
    cmd: kubectl get pods -n cert-manager
  register: result
  ignore_errors: yes
  no_log: True

- debug:
    msg: Removing cert-manager pods...
  when: result.stdout != ""

- name: Uninstallation of cert-manager
  shell:
# yamllint disable rule:line-length
    cmd: kubectl delete -f https://github.com/jetstack/cert-manager/releases/download/v0.15.0/cert-manager.yaml
  ignore_errors: 'True'
  when: result.stdout != ""
