CREATE USER inventory WITH PASSWORD 'PASSWORD_VALUE' CREATEDB;
CREATE DATABASE inventorydb
    WITH 
    OWNER = inventory
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE USER appo WITH PASSWORD 'PASSWORD_VALUE' CREATEDB;
CREATE DATABASE appodb
    WITH 
    OWNER = appo
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE USER apm WITH PASSWORD 'PASSWORD_VALUE' CREATEDB;
CREATE DATABASE apmdb
    WITH 
    OWNER = apm
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
