# Copyright 2020 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# cadvisor pod
---
apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  namespace: default
  labels:
    app: cadvisor
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
spec:
  containers:
    - image: unibaktr/cadvisor:v0.36.0
      imagePullPolicy: Always
      name: cadvisor-pod
      ports:
        - containerPort: 8080
          hostPort: 8081
          protocol: TCP
      resources:
        requests:
          memory: 200Mi
          cpu: 150m
        limits:
          memory: 2000Mi
          cpu: 300m
      volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
      # yamllint disable-line rule:key-duplicates
      volumeMounts:
        - mountPath: /var/run
          name: varrun
          readOnly: true
      # yamllint disable-line rule:key-duplicates
      volumeMounts:
        - mountPath: /sys
          name: sys
          readOnly: true
      # yamllint disable-line rule:key-duplicates
      volumeMounts:
        - mountPath: /var/lib/docker
          name: varlibdocker
          readOnly: true
      # yamllint disable-line rule:key-duplicates
      volumeMounts:
        - mountPath: /dev/disk
          name: devdisk
          readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
    - name: rootfs
      hostPath:
        path: /
  # yamllint disable-line rule:key-duplicates
  volumes:
    - name: varrun
      hostPath:
        path: /var/run
  # yamllint disable-line rule:key-duplicates
  volumes:
    - name: sys
      hostPath:
        path: /sys
  # yamllint disable-line rule:key-duplicates
  volumes:
    - name: varlibdocker
      hostPath:
        path: /var/lib/docker
  # yamllint disable-line rule:key-duplicates
  volumes:
    - name: devdisk
      hostPath:
        path: /dev/disk
