# Copyright 2021 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
### MUNO edge installation ###

- name: Check edgegallery tar ball present
  stat:
    path: /tmp/eg_download/deploy/EdgeGallery-v1.1.1-edge-x86.tar.gz
  register: edge_tar_var

- name: Download 1.1 edgegallery x86 edge
# yamllint disable rule:line-length
  command: wget https://edgegallery.obs.cn-east-3.myhuaweicloud.com/releases/v1.1.1/x86/EdgeGallery-v1.1.1-edge-x86.tar.gz
# yamllint disable rule:line-length
  args:
    chdir: /tmp/eg_download/deploy/
  when: not edge_tar_var.stat.exists

- name: Untar Edgegallery offline edge tar file
  command: tar -xvf EdgeGallery-v1.1.1-edge-x86
  args:
    chdir: /tmp/eg_download/deploy/
  when: not edge_tar_var.stat.exists

- name: Set inventory file for muno edge
# yamllint disable rule:line-length
  command: scp root@{{ OCD_IP }}:"{{playbook_dir}}"/muno-config/edge/hosts-muno-edge .
# yamllint disable rule:line-length
  args:
    chdir: "{{playbook_dir}}"

- name: Set var.yml file for muno edge
# yamllint disable rule:line-length
  command: scp root@{{ OCD_IP }}:"{{playbook_dir}}"/muno-config/edge/var.yml .
# yamllint disable rule:line-length
  args:
    chdir: "{{playbook_dir}}"

- name: Install edgegallery edge
  shell:
    # yamllint disable rule:line-length
    cmd: ansible-playbook --inventory hosts-muno-edge -e "ansible_user=root" eg_edge_aio_install.yml >> muno_edge_log
    # yamllint disable rule:line-length
    chdir: /tmp/eg_download/deploy/EdgeGallery-v1.1.1-edge-x86/install
  when: ansible_architecture == 'x86_64'
